name: geapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.20.2
  fluttertoast: ^8.2.11
  uuid: ^4.5.1
  shared_preferences: ^2.5.1
  sqflite: ^2.4.1
  path: ^1.9.0
  mask_text_input_formatter: ^2.9.0
  flutter_multi_formatter: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/jsons/estados-com-cidades.json
    - assets/images/no_image.png
